baseURL = 'https://cnt-orbita.ru/'
languageCode = 'ru-RU'
title = 'СНТ "Орбита"'
theme = "hugo-theme-stack"
DefaultContentLanguage = "ru"

[Params.colorScheme]
toggle=false
default="light"

[Params.footer]
since=2023